/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package menu_01_jm;

import br.com.jmary.home.Home;
import br.com.jmary.utilidades.Exportando;
import br.com.jmary.utilidades.JOPM;
import br.com.jmary.visualizador_imagens.Visualizador_Indice;
import home_controle_menus_norte.Controle_de_Alterar_Menu_Norte;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author AnaMariana
 */
public class Menu_1_JM_Perguntas_e_Respostas extends javax.swing.JPanel {
    private static final long serialVersionUID = 1L;
    
    Home Home;
    Controle_de_Alterar_Menu_Norte Controle_de_Alterar_Menu_Norte;
    //Sistema_Home  Sistema_Home;
    
    Alterar_Seta_Submenu Alterar_Seta_Submenu;

    /**
     * Creates new form PnHomeDesigner
     * @param Home2
     * @param Controle_de_Alterar_Menu_Norte2
     */
    public Menu_1_JM_Perguntas_e_Respostas( Home Home2, Controle_de_Alterar_Menu_Norte Controle_de_Alterar_Menu_Norte2 ) {
        initComponents();
        ((BasicInternalFrameUI)Fonema_E_Letra_Frame_Interno.getUI()).setNorthPane(null); //retirar o painel superior 
        
        Home = Home2;
        Controle_de_Alterar_Menu_Norte = Controle_de_Alterar_Menu_Norte2;
        //Sistema_Home  = Fonema_E_Letra_Home2;
        
        //Habilita troca de seta
        Alterar_Seta_Submenu = new Alterar_Seta_Submenu( this, Controle_de_Alterar_Menu_Norte, Home );
                        
        inicio();
    }
    
    private void inicio(){
        
        //mnConfiguracoes.setVisible(false);        
        Home.Home_Frame_Interno.setJMenuBar( Fonema_E_Letra_Barra_Menu );               
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Fonema_E_Letra_Frame_Interno = new javax.swing.JInternalFrame();
        Fonema_E_Letra_Barra_Menu = new javax.swing.JMenuBar();
        menu_seta = new javax.swing.JMenu();
        menu_ajuda = new javax.swing.JMenu();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        menu_ciencias_humanas3 = new javax.swing.JMenu();
        jMenuItem11 = new javax.swing.JMenuItem();
        menu_maimais = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem5 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItem6 = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        jMenuItem2 = new javax.swing.JMenuItem();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        Fonema_E_Letra_Frame_Interno.setBorder(null);
        Fonema_E_Letra_Frame_Interno.setVisible(true);

        menu_seta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/seta_para_cima.png"))); // NOI18N
        menu_seta.setToolTipText("Ocultar Submenu");
        menu_seta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menu_setaMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menu_setaMousePressed(evt);
            }
        });
        Fonema_E_Letra_Barra_Menu.add(menu_seta);

        menu_ajuda.setText("Ajuda");
        menu_ajuda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menu_ajudaMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menu_ajudaMousePressed(evt);
            }
        });
        menu_ajuda.add(jSeparator3);

        Fonema_E_Letra_Barra_Menu.add(menu_ajuda);

        menu_ciencias_humanas3.setText("Ciências");
        menu_ciencias_humanas3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menu_ciencias_humanas3MouseEntered(evt);
            }
        });

        jMenuItem11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/iconeAlfabetização.png"))); // NOI18N
        jMenuItem11.setText("Leitura e Aprendizagem");
        jMenuItem11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jMenuItem11MouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuItem11MousePressed(evt);
            }
        });
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        menu_ciencias_humanas3.add(jMenuItem11);

        Fonema_E_Letra_Barra_Menu.add(menu_ciencias_humanas3);

        menu_maimais.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/maismais.gif"))); // NOI18N
        menu_maimais.setText("++");
        menu_maimais.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menu_maimaisMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menu_maimaisMousePressed(evt);
            }
        });

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/sql.png"))); // NOI18N
        jMenuItem1.setText("Conexão Banco de Dados");
        jMenuItem1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jMenuItem1MouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuItem1MousePressed(evt);
            }
        });
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menu_maimais.add(jMenuItem1);
        menu_maimais.add(jSeparator1);

        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_printer.png"))); // NOI18N
        jMenuItem5.setText("Configurar Impressora");
        jMenuItem5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jMenuItem5MouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuItem5MousePressed(evt);
            }
        });
        menu_maimais.add(jMenuItem5);
        menu_maimais.add(jSeparator2);

        jMenuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/som.png"))); // NOI18N
        jMenuItem6.setText("Matéria/Categoria/Subcategoria/Assunto");
        jMenuItem6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jMenuItem6MouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuItem6MousePressed(evt);
            }
        });
        menu_maimais.add(jMenuItem6);
        menu_maimais.add(jSeparator4);

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/som.png"))); // NOI18N
        jMenuItem2.setText("Visualizador de Imagem");
        jMenuItem2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuItem2MousePressed(evt);
            }
        });
        menu_maimais.add(jMenuItem2);

        Fonema_E_Letra_Barra_Menu.add(menu_maimais);

        Fonema_E_Letra_Frame_Interno.setJMenuBar(Fonema_E_Letra_Barra_Menu);

        javax.swing.GroupLayout Fonema_E_Letra_Frame_InternoLayout = new javax.swing.GroupLayout(Fonema_E_Letra_Frame_Interno.getContentPane());
        Fonema_E_Letra_Frame_Interno.getContentPane().setLayout(Fonema_E_Letra_Frame_InternoLayout);
        Fonema_E_Letra_Frame_InternoLayout.setHorizontalGroup(
            Fonema_E_Letra_Frame_InternoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 563, Short.MAX_VALUE)
        );
        Fonema_E_Letra_Frame_InternoLayout.setVerticalGroup(
            Fonema_E_Letra_Frame_InternoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fonema_E_Letra_Frame_Interno)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Fonema_E_Letra_Frame_Interno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 82, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void menu_setaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_setaMousePressed
        Home.tocarSon.tocar( 51 );
        Alterar_Seta_Submenu.tabJanelaSubmenu( this.menu_seta );
    }//GEN-LAST:event_menu_setaMousePressed

    
    private void menu_ajudaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_ajudaMousePressed
        //Sistema_Home.adicionarSubmenu(new Submenu2( Sistema_Home ) );     
    }//GEN-LAST:event_menu_ajudaMousePressed

    private void menu_maimaisMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_maimaisMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_menu_maimaisMousePressed

    private void jMenuItem1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem1MousePressed
        new Thread() {   @Override public void run() { try { Thread.sleep( 1 );
            /*
            if( Administrador.mapaComandos.get("ACESSO_PAIS") != null ) {
                
                //Sistema_Home.adicionarSubmenu(new Configuracoes( Sistema_Home ) ); 
                
                Sistema_Home.Home.ControleTabs.AddTabsAoHome("Pais", "/sistema_imagens/livroTp.gif", new Pais_Home( Sistema_Home.Home ) );                   
            }
            else{ JOPM JOptionPaneMod = new JOPM( 2, "USUÁRIO SEM AUTORIZAÇÂO, "
                    + "\nO USUÁRIO LOGADO NÃO TEM PERMISSÃO PARA REALIZAR ESTA AÇÃO"
                    + "\nUSUÁRIO LOGADO: " + Bean_Usuario_Logado.NOMECOMPLETO
                    + "\nSOLICITE AUTORIZAÇÃO AO ADMINISTRADOR"
                    + "\n", "USUÁRIO SEM AUTORIZAÇÂO" );
            }*/
        } catch( Exception e ){ } } }.start();
    }//GEN-LAST:event_jMenuItem1MousePressed

    private void jMenuItem5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem5MousePressed
        new Thread() {   @Override public void run() { try { Thread.sleep( 1 );
            
            //if( Administrador.mapaComandos.get("ACESSO_CEP") != null ) {
                
                //Sistema_Home.adicionarSubmenu(new Configuracoes( Sistema_Home ) ); 
                
                //Sistema_Home.Home.ControleTabs.AddTabsAoHome("IMPORTAR/EXPORTAR", "/sistema_imagens/livroTp.gif", new Importar_Exportar_Home( Sistema_Home.Home ) );                   
            /*}
            else{ JOPM JOptionPaneMod = new JOPM( 2, "USUÁRIO SEM AUTORIZAÇÂO, "
                    + "\nO USUÁRIO LOGADO NÃO TEM PERMISSÃO PARA REALIZAR ESTA AÇÃO"
                    + "\nUSUÁRIO LOGADO: " + Bean_Usuario_Logado.NOMECOMPLETO
                    + "\nSOLICITE AUTORIZAÇÃO AO ADMINISTRADOR"
                    + "\n", "USUÁRIO SEM AUTORIZAÇÂO" );
            }*/
        } catch( Exception e ){ } } }.start();
    }//GEN-LAST:event_jMenuItem5MousePressed

    private void jMenuItem6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem6MousePressed
        Home.tocarSon.tocar( 51 );
        try{

            Home.Controle_de_Alterar_Menu_Norte.adicionarSubmenu(new Submenu_1_JM_Criar_Leitura_e_Aprendizagem( Home, Home.Controle_de_Alterar_Menu_Norte ) );

        } catch( Exception e ){ e.printStackTrace(); JOPM JOptionPaneMod = new JOPM( 2, "adicionarSubmenu( Component c ), \n"
            + e.getMessage() + "\n", "Classe: " + "Controle_de_Alterar_Menu_Norte" ); }
    }//GEN-LAST:event_jMenuItem6MousePressed

    private void menu_maimaisMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_maimaisMouseEntered
        Home.tocarSon.tocar( 51 );
    }//GEN-LAST:event_menu_maimaisMouseEntered

    private void jMenuItem1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem1MouseEntered
        Home.tocarSon.tocar( 51 );
    }//GEN-LAST:event_jMenuItem1MouseEntered

    private void jMenuItem5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem5MouseEntered
        Home.tocarSon.tocar( 51 );
    }//GEN-LAST:event_jMenuItem5MouseEntered

    private void jMenuItem6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem6MouseEntered
        Home.tocarSon.tocar( 51 );
    }//GEN-LAST:event_jMenuItem6MouseEntered

    private void menu_ajudaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_ajudaMouseEntered
        Home.tocarSon.tocar( 51 );
    }//GEN-LAST:event_menu_ajudaMouseEntered

    private void menu_setaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_setaMouseEntered
        Home.tocarSon.tocar( 51 );
    }//GEN-LAST:event_menu_setaMouseEntered

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem11MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem11MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem11MouseEntered

    private void jMenuItem11MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem11MousePressed
        
        Home.tocarSon.tocar( 51 );
        try{

            Home.Controle_de_Alterar_Menu_Norte.adicionarSubmenu(new Submenu_1_JM_ADS_Adicao_Leitura_e_Aprendizagem( Home, Home.Controle_de_Alterar_Menu_Norte ) );

        } catch( Exception e ){ e.printStackTrace(); JOPM JOptionPaneMod = new JOPM( 2, "adicionarSubmenu( Component c ), \n"
            + e.getMessage() + "\n", "Classe: " + "Controle_de_Alterar_Menu_Norte" ); }
    
    }//GEN-LAST:event_jMenuItem11MousePressed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void menu_ciencias_humanas3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_ciencias_humanas3MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_menu_ciencias_humanas3MouseEntered

    Exportando Exportando;
    private void jMenuItem2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem2MousePressed
        /*
        Home.tocarSon.tocar( 51 );
        try{
            
            Home.Controle_de_Alterar_Menu_Norte.adicionarSubmenu(new Visualizador_de_Imagens_Menu2( Home, Home.Controle_de_Alterar_Menu_Norte ) );
            
        } catch( Exception e ){ e.printStackTrace(); JOPM JOptionPaneMod = new JOPM( 2, "adicionarSubmenu( Component c ), \n"
                + e.getMessage() + "\n", "Classe: " + "Controle_de_Alterar_Menu_Norte" ); }
        */
        Home.tocarSon.tocar( 51 );
        new Thread() {   @Override public void run() { try { Thread.sleep( 1 );

            Home.ControleTabs.AddTabsAoHome("Visualizador de Imagens", "/imagens_internas/livroTp.gif", new Visualizador_Indice(Home) ); 

        } catch( Exception e ){ } } }.start();
    }//GEN-LAST:event_jMenuItem2MousePressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar Fonema_E_Letra_Barra_Menu;
    private javax.swing.JInternalFrame Fonema_E_Letra_Frame_Interno;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JMenu menu_ajuda;
    private javax.swing.JMenu menu_ciencias_humanas3;
    private javax.swing.JMenu menu_maimais;
    private javax.swing.JMenu menu_seta;
    // End of variables declaration//GEN-END:variables
            
}
